---
version: "3"
services:
  app:
    build: .
    command: ""
    volumes:
      - ./db:/db
    links:
      - database
    ports:
      - "8008:8008"

  stream:
    build: .
    command: ""
    volumes:
      - ./db:/db
    links:
      - database
    ports:
      - "8009:8008"

  database:
    image: postgres:9.6.3-alpine
    environment:
      POSTGRES_PASSWORD: ula
      POSTGRES_USER: ula
      POSTGRES_DB: tasks
